name: Run Tests

on:
  push:
    branches:
      - main
    tags:
      - "v*"

  pull_request:
    branches:
      - main

  schedule:
    # Every day at 1.00 UTC.
    - cron: "0 1 * * *"

# If you trigger a new workflow while the previous one is running,
# this will cancel the previous one.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FLY_API_TOKEN: ${{ secrets.FLY_AUTH_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      # Use matrix strategy to run the tests on multiple Py versions on multiple OSs.
      matrix:
        python-version: ["3.10"]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install the Dependencies
        run: |
          echo "Installing the dependencies..."
          python -m pip install -r requirements.txt -r requirements-dev.txt
      - name: Check Linter
        run: |
          echo "Checking linter formatting..."
          make lint-check
      - name: Run Tests
        run: |
          echo "Running the tests..."
          python -m pytest -v -s

  deploy:
    if: startsWith(github.event.ref, 'refs/tags/v')
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
